/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:129f4761-cc3d-4e8c-b149-52c332ce7e87",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_E6IL6gYJB",
    "aws_user_pools_web_client_id": "1tsstu1hu3cs1btug0td4aeg81",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pqwqwmseefcl5n4gvphtyiyztu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7e22tcs4dbcsffdj2wc5y7pxrq"
};


export default awsmobile;
